import numpy as np
from typing import Dict, Any

from ml.classifier import get_model, predict_credit_score


def get_credit_score(features: Dict) -> Dict[str, Any]:
    model, feature_names = get_model()

    if model is None:
        return {"error": "Model not loaded. Run python ml/train_classifier.py first."}

    feature_vector = {name: features.get(name, 0.0) for name in feature_names}

    raw_score = predict_credit_score(feature_vector)
    credit_score = max(300, min(850, int(raw_score)))

    importances = getattr(model, "feature_importances_", None)
    factor_breakdown = {}

    if importances is not None and len(importances) == len(feature_names):
        sorted_idx = np.argsort(importances)[::-1]
        factor_breakdown = {
            feature_names[i]: round(float(importances[i] * 100), 2)
            for i in sorted_idx[:5]
        }

    if credit_score >= 700:
        risk_level = "Low"
    elif credit_score >= 550:
        risk_level = "Medium"
    else:
        risk_level = "High"

    if credit_score >= 750:
        grade = "A"
    elif credit_score >= 650:
        grade = "B"
    elif credit_score >= 550:
        grade = "C"
    elif credit_score >= 450:
        grade = "D"
    else:
        grade = "E"

    return {
        "credit_score": credit_score,
        "score_range": "300-850",
        "risk_level": risk_level,
        "grade": grade,
        "factor_breakdown": factor_breakdown,
        "message": f"Your alternative credit score is {credit_score} ({risk_level} risk).",
        "note": "This score is generated by a RandomForest ML model trained on financial behavior patterns."
    }