import pandas as pd
import pickle
import json
import numpy as np
from typing import Dict, Any

# Load the trained RandomForest model once when the module is imported
model = None
feature_names = []

try:
    with open("app/ml/credit_model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("app/ml/feature_names.json", "r") as f:
        feature_names = json.load(f)
    print("✅ ML Credit Scoring Model loaded successfully!")
except FileNotFoundError:
    print("⚠️ Model files not found. Run: python app/ml/train.py")
except Exception as e:
    print(f"⚠️ Error loading model: {e}")

def get_credit_score(features: Dict) -> Dict[str, Any]:
    """
    Uses the trained RandomForest model to generate a credit score (300-850)
    with explainable factor breakdown.
    """
    if model is None:
        return {"error": "Model not loaded. Please run python app/ml/train.py first."}

    # Ensure all required features are present (fill missing with 0.0)
    feature_vector = {name: features.get(name, 0.0) for name in feature_names}
    
    # Convert to DataFrame for prediction
    df_input = pd.DataFrame([feature_vector])

    # Get prediction from ML model
    raw_score = model.predict(df_input)[0]
    credit_score = max(300, min(850, int(round(raw_score))))

    # Explainability: Feature importance (top contributors)
    importances = model.feature_importances_
    sorted_idx = np.argsort(importances)[::-1]
    factor_breakdown = {
        feature_names[i]: round(float(importances[i] * 100), 2)
        for i in sorted_idx[:5]   # Show top 5 most important factors
    }

    # Risk categorization
    if credit_score >= 700:
        risk_level = "Low"
    elif credit_score >= 550:
        risk_level = "Medium"
    else:
        risk_level = "High"


    # Add this inside get_credit_score(), after risk_level
    if credit_score >= 750:
        grade = "A"
    elif credit_score >= 650:
        grade = "B"
    elif credit_score >= 550:
        grade = "C"
    elif credit_score >= 450:
        grade = "D"
    else:
        grade = "E"

    return {
        "credit_score": credit_score,
        "score_range": "300-850",
        "risk_level": risk_level,
        "grade" : grade,
        "factor_breakdown": factor_breakdown,
        "message": f"Your alternative credit score is {credit_score} ({risk_level} risk).",
        "note": "This score is generated by a RandomForest ML model trained on financial behavior patterns."
    }